---
title: "Points For and Against"
author: "John Jurica"
date: "2024-08-19"
output: html_document
---


```{r load packages}

library(tidyverse)
library(readr)
library(knitr)
library(kableExtra)

```
Some data was formatted in Excel. Personal Identifiers were removed.


```{r read in the data}


teams_info_2023_thru_2014_updated <- read_csv("teams_info_2023_thru_2014_updated_csv.csv", 
  col_types = cols(
    `Team ID` = col_double(),               
    `Owner First Name` = col_character(),   
    `Is League Creator` = col_character(),  
    `Playoff Seed` = col_double(),          
    `Final Rank` = col_double(),            
    `Wins` = col_double(),                  
    `Losses` = col_double(),                
    `Ties` = col_double(),                  
    `Points For` = col_double(),            
    `Points Against` = col_double(),        
    `Year` = col_double()                   
  )
)

```

Standardizing first names

```{r standardizes first names}
teams_info_2023_thru_2014_updated <- teams_info_2023_thru_2014_updated %>%
  mutate(first_name_lower = ifelse(`Owner First Name` == "JD" , toupper(`Owner First Name`),
                                   ifelse(`Team ID` == 9, "Jimmy",  str_to_title(`Owner First Name`))))


```


Chart with Average Points For and Points Against

```{r Avg Points For and Against}

# Create the summary table
summary_table <- teams_info_2023_thru_2014_updated %>%
  group_by(first_name_lower) %>%
  summarise(
    avg_points_against = round(mean(`Points Against`), 2),
    avg_points_for = round(mean(`Points For`), 2)
  ) %>%
  arrange(desc(avg_points_for))

# Rename columns for readability
summary_table <- summary_table %>%
  rename(
    `Team Name` = first_name_lower,
    `Average Points Against` = avg_points_against,
    `Average Points For` = avg_points_for
  )

# Display the table with kable and kableExtra with custom width
summary_table <- kable(summary_table, 
      caption = "Average Points For and Against by Team", 
      align = c("l", "c", "c")) %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width = TRUE, # Set to TRUE to make the table wider
    position = "center"
  ) %>%
  column_spec(1, width = "15em") %>%   
  column_spec(2, width = "15em") %>%  
  column_spec(3, width = "15em") %>%  # 
  row_spec(0, bold = TRUE, color = "white", background = "#4CAF50", extra_css = "padding: 20px;")

summary_table
```

Add a column to main dataset to indicate winner for ease of graphing

```{r Add a column for the winner each season}

teams_info_2023_thru_2014_updated <- 
  teams_info_2023_thru_2014_updated %>%
  mutate(winner_y_n = ifelse(`Final Rank` == 1, "yes", "no"))


```

Graph of Points For and Against per season. Removed player who only played a single season


```{r, fig.width=10, fig.height=6}
library(ggplot2)
library(dplyr)

scores_over_time_final <- teams_info_2023_thru_2014_updated %>%
  filter(first_name_lower != "Claude") %>%
  ggplot() +
  geom_point(aes(y = `Points For`, x = Year, shape = winner_y_n, color = "Points For")) +
  geom_line(aes(y = `Points For`, x = Year, color = "Points For")) +
  geom_point(aes(y = `Points Against`, x = Year, shape = winner_y_n, color = "Points Against")) +
  geom_line(aes(y = `Points Against`, x = Year, color = "Points Against")) +
  labs(
    title = "Scores per Year",
    subtitle = "Blue = Points For; Red = Points Against; Triangle = Winner",
    y = "Points",
    color = "Legend",
    shape = "Winner"
  ) +
  scale_color_manual(values = c("Points For" = "blue", "Points Against" = "red")) +
  facet_wrap(~first_name_lower) +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 45, hjust = 1.0),
    panel.spacing = unit(1, "lines"),
    aspect.ratio = 1/2
  )

scores_over_time_final
```

